  CREATE TABLE [dbo].[Log](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HoraInsercao] [datetime] NOT NULL,
) ON [PRIMARY]

  INSERT INTO [TESTE].[DBO].[LOG] VALUES (GETDATE())
  INSERT INTO [TESTE].[DBO].[LOG] VALUES (GETDATE())
  INSERT INTO [TESTE].[DBO].[LOG] VALUES (GETDATE())